export const ErrorCode = {
  // General
  UNKNOWN: "UNKNOWN",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  ENV_ERROR: "ENV_ERROR",

  // Business
  PARAMETER_ERROR: "PARAMETER_ERROR",
  CONCURRENT_UPDATE: "CONCURRENT_UPDATE",
  STATUS_CONFLICT: "STATUS_CONFLICT",
  SYNC_CANCELED: "SYNC_CANCELED",
  SYNC_CIRCUIT_BREAKER: "SYNC_CIRCUIT_BREAKER",

  // Database
  DB_UNIQUE_VIOLATION: "DB_UNIQUE_VIOLATION",
  DB_FOREIGN_KEY: "DB_FOREIGN_KEY",
  DB_ERROR: "DB_ERROR",

  // asset
  SIZE_LIMIT_EXCEEDED: "SIZE_LIMIT_EXCEEDED",
  // integration
  EMPTY_RESPONSE_BODY: "EMPTY_RESPONSE_BODY",
  FEATURE_GATE_DISABLED: "FEATURE_GATE_DISABLED",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
