export const ErrorCode = {
  UNKNOWN: "UNKNOWN",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  ENV_ERROR: "ENV_ERROR",
  PARAMETER_ERROR: "PARAMETER_ERROR",
  CONFLICT: "CONFLICT",
  DB_UNIQUE_VIOLATION: "DB_UNIQUE_VIOLATION",
  DB_FOREIGN_KEY: "DB_FOREIGN_KEY",
  DB_ERROR: "DB_ERROR",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
